x-dns: &default-dns
  dns:
    - 8.8.8.8
    - 8.8.4.4

networks:
  app-net:
    driver: bridge

services:
  ui-app:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./ui-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./ui-app:/app
      - /app/node_modules

  api-gateway:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - USER_URL=http://user:3100
      - AVATAR_URL=http://avatar:3200
      - JOB_MANAGER_URL=http://job-manager:3300
      - VOICE_URL=http://voice:3600

  user:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./user
    ports:
      - "3100:3100"
    volumes:
      - ./user:/app
      - /app/node_modules
      - ./gcp-json-key.json:/root/.config/gcloud/gcp-json-key.json:ro
    environment:
      - PORT=3100
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/gcp-json-key.json
      - PROJECT_ID=loom24-mvp
      - DB_NAME=ai-avatar-db
      - COLLECTION_NAME=users

  avatar:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./avatar
    ports:
      - "3200:3200"
    volumes:
      - ./avatar:/app
      - /app/node_modules
      - ./gcp-json-key.json:/root/.config/gcloud/gcp-json-key.json:ro
    environment:
      - PORT=3200
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/gcp-json-key.json
      - PROJECT_ID=loom24-mvp
      - DB_NAME=ai-avatar-db
      - USERS_COLLECTION_NAME=users
      - AVATARS_COLLECTION_NAME=avatars
      - JOB_MANAGER_URL=http://job-manager:3300

  job-manager:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./job-manager
    ports:
      - "3300:3300"
    volumes:
      - ./job-manager:/app
      - /app/node_modules
      - ./gcp-json-key.json:/root/.config/gcloud/gcp-json-key.json:ro
    environment:
      - PORT=3300
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/gcp-json-key.json
      - PROJECT_ID=loom24-mvp
      - DB_NAME=ai-avatar-db
      - JOBS_COLLECTION_NAME=jobs
      - GEN_QWEN_EDIT_2511_TOPIC=gen-qwen-edit-2511
      - AI_TOOLKIT_TOPIC=ai-toolkit
      - RUNPOD_URL=http://runpod:3500
      - LLM_REQUEST_URL=http://llm-request:3700

  ai-model-result:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./ai-model-result
    volumes:
      - ./ai-model-result:/app
      - /app/node_modules
      - ./gcp-json-key.json:/root/.config/gcloud/gcp-json-key.json:ro
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/gcp-json-key.json
      - PROJECT_ID=loom24-mvp
      - AVATAR_URL=http://avatar:3200
      - JOB_MANAGER_URL=http://job-manager:3300
      - SUBSCRIPTION_ID=ai-model-result-sub

  runpod:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./runpod
    ports:
      - "3500:3500"
    volumes:
      - ./runpod:/app
      - /app/node_modules
      - ./gcp-json-key.json:/root/.config/gcloud/gcp-json-key.json:ro
    environment:
      - PORT=3500
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/gcp-json-key.json
      - PROJECT_ID=loom24-mvp
      - RUNPOD_API_URL=https://rest.runpod.io
      - NETWORK_VOLUME_ID=0p9gfckg9x
      - TEXT_IMAGE_TO_IMAGE_TEMPLATE_ID=m1bv0g3gi7
      - REGION=US-CA-2

  voice:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./voice
    ports:
      - "3600:3600"
    volumes:
      - ./voice:/app
      - /app/node_modules
      - ./gcp-json-key.json:/root/.config/gcloud/gcp-json-key.json:ro
    environment:
      - PORT=3600
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/gcp-json-key.json
      - PROJECT_ID=loom24-mvp
      - DB_NAME=ai-avatar-db
      - BUCKET_NAME=loom24-mvp.firebasestorage.app

  llm-request:
    <<: *default-dns
    networks:
      - app-net
    build:
      context: ./llm-request
    ports:
      - "3700:3700"
    volumes:
      - ./llm-request:/app
      - /app/node_modules
      - ./gcp-json-key.json:/root/.config/gcloud/gcp-json-key.json:ro
    environment:
      - PORT=3700
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/gcp-json-key.json
      - PROJECT_ID=loom24-mvp
      - BUCKET_NAME=loom24-mvp.firebasestorage.app
