# syntax=docker/dockerfile:1
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir poetry
ENV POETRY_VIRTUALENVS_CREATE=false

COPY pyproject.toml poetry.lock ./

RUN --mount=type=secret,id=gcp_key \
    pip install --no-cache-dir keyring keyrings.google-artifactregistry-auth && \
    GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_key \
    poetry install --no-root --no-interaction

COPY . .

CMD ["bash", "-c", "python -m watchfiles 'python main.py' . 2> >(grep -vF 'NNPACK' >&2)"]
