MIN_VIDEO_DURATION_SEC = 3
MAX_VIDEO_DURATION_SEC = 10
MAX_VIDEO_AUDIO_RECORDING_SEC = 10
MAX_VIDEO_AUDIO_TEXT_CHARS = 150
MIN_PROMPT_TEXT_CHARS = 5
MAX_PROMPT_TEXT_CHARS = 1000
MIN_AUDIO_TEXT_CHARS = 2
MAX_AUDIO_TEXT_CHARS = 500
