# syntax=docker/dockerfile:1
FROM node:22-slim

WORKDIR /app

COPY package.json package-lock.json* .npmrc ./

RUN --mount=type=secret,id=gcp_key \
    GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_key \
    npx --yes google-artifactregistry-auth && \
    npm install

CMD ["npm", "run", "dev"]
